<?php

namespace App\Repositories;

use App\Models\Partner;
use App\Repositories\Base\CrudBaseRepository;
use App\Services\ImageService;

class PartnerRepository extends  CrudBaseRepository
{
    public function __construct() {
        parent::__construct(new Partner());
        $this->filterable = [
            "search" =>[

            ],
        ];
    }

    public function edit(int $id, $data){

        $partner = $this->findByID($id);

        $old_image  = $partner->image;
        $image  = $old_image ;
        if(isset($data['image'])){
            $image = ImageService::update_image($data['image'] , $old_image , 'partner');

        }
        return   parent::edit($id , [
            'image'=>$image,
        ]);


    }

    public function create($data)
    {
        $image = ImageService::upload_image($data['image'] , 'partner');

        return parent::create([
            'image'=>$image,
        ]);
    }

    public function delete(int $id)
    {
        $partner = $this->findByID($id);
        ImageService::delete_image($partner->image);
        return parent::delete($id); // TODO: Change the autogenerated stub
    }

}
